armory/spinnaker-operator

cmd/manager/main.go
pkg/apis/spinnaker/v1alpha1/config.go
pkg/apis/spinnaker/v1alpha1/interface.go
pkg/controller/spinnakerservice/configwatcher.go
pkg/controller/spinnakerservice/spinnakerservice_controller.go
pkg/controller/spinnakerservice/status.go
pkg/controller/spinnakervalidating/gvk.go
pkg/controller/spinnakervalidating/spinnakervalidating_controller.go
pkg/deployer/changedetector/changedetector.go
pkg/deployer/changedetector/expose_lb.go
pkg/deployer/changedetector/halconfig.go
pkg/deployer/changedetector/x509.go
pkg/deployer/deploy.go
pkg/deployer/save.go
pkg/deployer/transformer/common_test.go
pkg/deployer/transformer/expose_lb.go
pkg/deployer/transformer/expose_lb_test.go
pkg/deployer/transformer/owner.go
pkg/deployer/transformer/serverport.go
pkg/deployer/transformer/serverport_test.go
pkg/deployer/transformer/target.go
pkg/deployer/transformer/target_test.go
pkg/deployer/transformer/transformer.go
pkg/deployer/transformer/x509.go
pkg/deployer/transformer/x509_test.go
pkg/operator/operator.go
pkg/validate/single_namespace.go
pkg/validate/validate.go

- Transformers get a name
- SpinnakerConfig is added to the transformer instead of as param
- Validators, Transformers, and ChangeDetectors use interface

feat(interface): Use interfaces for SpinnakerService

---

pkg/accounts/account/account.go
pkg/accounts/accounts.go
pkg/accounts/kubernetes/kubernetes.go
pkg/accounts/kubernetes/validator.go
pkg/apis/spinnaker/v1alpha2/spinnakeraccount_types.go
pkg/controller/accountvalidating/accountvalidating_controller.go
pkg/controller/spinnakeraccount/spinnakeraccount_controller.go
pkg/secrets/secrets.go
pkg/validate/accounts.go

- Start Kubernetes account validation
- Support secret file decryption and validate file exists

feat(account): hook account validation

---

deploy/crds/spinnaker.io_spinnakerservices_crd.yaml
pkg/apis/spinnaker/v1alpha2/spinnakerservice_types.go
pkg/apis/spinnaker/v1alpha2/zz_generated.deepcopy.go
pkg/apis/spinnaker/v1alpha2/zz_generated.openapi.go
pkg/deploy/spindeploy/changedetector/config.go

fix(crd/validation): config hash as map

---

pkg/deploy/spindeploy/transformer/accounts.go
pkg/deploy/spindeploy/transformer/accounts_test.go
pkg/deploy/spindeploy/transformer/secrets.go
pkg/deploy/spindeploy/transformer/secrets_test.go

- fix Kubernetes secrets when same secret requested more than once

fix(deploy/accounts): Add Spring profile on the output to allow for local

---

README.md
doc/managing-spinnaker.md
doc/options.md
doc/spinnaker-accounts.md
doc/uninstalling.md

I cleaned up some typos and clarity issues. This iteration is cleaner than what's in my docs.armory PR, so I will update that one.

docs(operator): copyedit github docs

---

integration_tests/env.go
integration_tests/integration_test.go
integration_tests/utils.go

Make default test variables like operator and halyard images configurable, instead of constants.

chore(tests): Make default values configurable

---

integration_tests/integration_test.go
integration_tests/testdata/spinnaker/overlay_profiles/spinnakerservice.yml
integration_tests/utils.go
pkg/deploy/spindeploy/transformer/secrets.go
pkg/deploy/spindeploy/transformer/secrets_test.go

Don't try to sanitize secrets in json files like packer templates.

fix(files): Don't convert json files to yaml

---

deploy/operator/basic/deployment.yaml
deploy/operator/cluster/deployment.yaml
integration_tests/integration_test.go

Updated the default Halyard container image to 0.4.x

chore(release): Updated halyard image tag to 0.4.x

---

pkg/deploy/spindeploy/transformer/stats.go
pkg/deploy/spindeploy/transformer/stats_test.go
pkg/deploy/spindeploy/transformer/transformer.go

Rename telemetry to stats due to spinnaker/halyard#1565

feat(stats): Rename telemetry to stats due to change in halyard

---

Makefile
pkg/bom/services.go
pkg/deploy/spindeploy/transformer/defaults.go
pkg/deploy/spindeploy/transformer/defaults_test.go
pkg/deploy/spindeploy/transformer/transformer.go
pkg/util/constants.go

Add `archaius.enabled: false` as a default in the java services if they are not defined in the profile.

feat(defaults): Add transform for profile default values

---

halyard-version
integration_tests/integration_test.go
integration_tests/testdata/spinnaker/overlay_secrets/kustomization.yml
integration_tests/testdata/spinnaker/overlay_secrets/secrets.yml
integration_tests/testdata/spinnaker/overlay_secrets/spinnaker-template.yml
integration_tests/testdata/spinnaker/overlay_validations/spinnakerservice-template.yml
integration_tests/utils.go
pkg/deploy/spindeploy/transformer/secrets.go
pkg/deploy/spindeploy/transformer/secrets_test.go
pkg/halyard/request.go
vendor/gopkg.in/yaml.v2/go.sum

* Mount k8s secrets env vars and volumes in `monitoring-daemon` containers
* Updated integration tests

fix(secrets): k8s secrets decrypted in halyard

---

pkg/deploy/spindeploy/transformer/defaults.go
pkg/deploy/spindeploy/transformer/defaults_test.go
pkg/inspect/getter.go
pkg/inspect/setter_test.go

cherry pick ae524466368ffcaab29aa533b511fa1366ab2320

fix(defaults): Use long delays instead of `archaius.enabled: false` to not break hystrix defaults (#141)

---

halyard-version
integration_tests/integration_test.go
integration_tests/testdata/spinnaker/base/spinnakerservice.yml

* chore(tests): Stepped base spinnaker version for int tests
* chore(release): Updated halyard version

chore(release): Updated halyard version (#143)

---

deploy/spinnaker/kustomize/kustomization.yml

Make kustomization.yml compatible with both the kustomize
binary and `kubectl kustomize`

fix(kustomize): Make kustomization.yml more compatible

---

pkg/deploy/spindeploy/save.go
pkg/deploy/spindeploy/transformer/secrets.go

During the dependencies upgrades, object type of Secrets
changed from v1.Secret to Unstructured. We need to cast
it to make secrets.go TransformManifests method work again.
Related: https://github.com/armory/spinnaker-operator/issues/245#issuecomment-1180613717

Fix transforming k8s secrets

---

.github/workflows/build.yml
.github/workflows/test.yml

TODO: dedupe the steps between jobs and share build output

chore(build): make sure forks can run tests, but not create releases

---

halyard-version

https://armory.atlassian.net/browse/BOB-30749

feat(halyard): bump version

---

.github/workflows/pr-build.yml

Created 2 different actions one for PRs and another for Master and releases

chore(build): split actions for PRs and master

---

.github/workflows/pr-build.yml
halyard-version

Related Halyard changes: https://github.com/armory-io/halyard/pull/70

chore(dependency): update upstream oss halyard version.

---

build-tools/Dockerfile
halyard-version

[BOB-31028](https://armory.atlassian.net/browse/BOB-31028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ)
[BOB-31028]: https://armory.atlassian.net/browse/BOB-31028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore(docker): update alpine images operator + halyard

---

halyard-version

Updating halyard as done from the forked PR https://github.com/armory/spinnaker-operator/pull/297
In the future we will need to update our workflows to allow PR from forked repo's.

chore(dependency): update upstream oss halyard version - ArmoryPR
